### ISSUE TITLE
Same hash for the same uploaded picture is added to the database

### ISSUE THREAD

**Issue by TiffanyVPhan** [CUBigDataClass/PicSure#7]
This issue occurs when a user uploads an image in the Camera Simulator by clicking the "Upload" button and then clicking on the "Upload" button again. This results in the same hash being added to the database twice.
![Screenshot from 2020-04-09 15-06-40](https://user-images.githubusercontent.com/43645733/78940843-bd102100-7a73-11ea-9442-65b3cb1f5acf.png)
Images 2, 3, and 4 are the same image added to the database with the same hash: "340d2955cae68c055fe7a83dead3d72fc64578582c47910b15032c5f2e712f97372467fd6677d5099444eb77c3e5b445e02026c7e53c62cae26658e1967adaa5". 

We should probably check for if the same hash is already in the database so we don't add the same one again to save space and redundancy!

**Comment by joshf26** [comment]
Oh yeah this is a good idea, but luckily Redis will handle this for us once we switch over :D

https://redis.io/commands/set
